### PR TITLE
Refactor android module

### PR DESCRIPTION
**Pull request by vonovak**
This can be thought of as the android version of this PR https://github.com/wonday/react-native-orientation-locker/pull/96/files that I opened earlier.

I removed a lot of code that was duplicated in the lock* methods, and factored it out into reusable functions.

I realize this is a rather big PR because I also renamed a few things, but I hope this will not make review more complicated. Here's a sample I have tested this with both android and ios

```js
import React, { PureComponent } from 'react';
import { View, Text as RNText } from 'react-native';
import Orientation from 'react-native-orientation-locker';

const Text = (props) => {
  return <RNText {...props} style={{ margin: 10 }} />;
};

export default class App extends PureComponent {
  componentDidMount() {
    Orientation.unlockAllOrientations();
    // Orientation.getAutoRotateState((rotationLock) => this.setState({ rotationLock }));

    Orientation.addOrientationListener(this._onOrientationDidChange);
    Orientation.addDeviceOrientationListener(this._onDeviceOrientationChanged);
    Orientation.addLockListener(this._onLockChange);
  }

  componentWillUnmount() {
    Orientation.removeOrientationListener(this._onOrientationDidChange);
    Orientation.removeLockListener(this._onLockChange);
  }

  _onOrientationDidChange = (orientation) => {
    console.warn('ui orientation changed', orientation);
  };

  _onDeviceOrientationChanged = (orientation) => {
    console.warn('device orientation changed', orientation);
  };

  _onLockChange = (orientation) => {
    console.warn('onLockChange', orientation);
  };

  render() {
    return (
      <View style={{ marginTop: 100 }}>
        <Text onPress={() => Orientation.lockToLandscape()}>lockToLandscape</Text>
        <Text onPress={() => Orientation.lockToLandscapeRight()}>lockToLandscapeRight</Text>
        <Text onPress={() => Orientation.lockToLandscapeLeft()}>lockToLandscapeLeft</Text>

        <Text onPress={() => Orientation.lockToPortrait()}>lockToPortrait</Text>
        <Text onPress={() => Orientation.lockToPortraitUpsideDown()}>lockToPortraitUpsideDown</Text>
        <Text onPress={() => Orientation.unlockAllOrientations()}>unlockAllOrientations</Text>
        <Text
          onPress={() => {
            Orientation.getDeviceOrientation((deviceOrientation) => {
              console.warn('Current Device Orientation: ', deviceOrientation);
            });
          }}
        >
          getDeviceOrientation
        </Text>
        <Text
          onPress={() => {
            Orientation.getOrientation((orientation) => {
              console.warn('Current UI Orientation: ', orientation);
            });
          }}
        >
          getOrientation
        </Text>
      </View>
    );
  }
}
```

### CODE REVIEW

**Comment by vonovak** [comment]
@wonday can you please review this? Thank you!

**Comment by vonovak** [comment]
@wonday sorry to ping you again, do you plan to take a look at this? Thanks

**Comment by wonday** [comment]
Thank you for your PR, 
But your modification seems change/lost something.

For example, 
in lockToPortrait(),  
In my code ```orientationDidChange``` event and ```lockDidChange``` event are sent.
In your code  only ```lockDidChange``` is sent.

I am not sure this OK or not, maybe someone is using the ```orientationDidChange``` event

**Comment by magrinj** [comment]
@wonday @vonovak I'm using `orientationDidChange` event when lock function is called, to retrieve the orientation state and update it on some components. This must be kept.

**Pull request closed without merging**
