### PR TITLE
Added check for broadcast receiver being unregistered

### PR DESCRIPTION
**Pull request by ruslan-h**
Added check for broadcast receiver being unregistered to avoid IllegalArgumentException, broadened catch from IllegalArgumentException to Exception for more stability

### CODE REVIEW

**Comment by maschad** [comment]
Nice catch, LGTM

**Comment by ruslan-h** [comment]
@wonday can you please have a look into suggested change? Thank you

**Comment by r0b0t3d** [comment]
LGTM

**Comment by ruslan-h** [comment]
Hi Wonday,

Can you please make a new release as well?
Thank you.

Ruslan

**Pull request merged**
