### PR TITLE
fix: update android file to avoid warning on NativeEventEmitter

### LINKED ISSUE #200: After upgrading to react 0.65 i'm getting ``new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method. NativeEventEmitter @ NativeEventEmitter.js:59`
I'm using the following packages
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-orientation-locker": "1.1.8"

Screenshot 2021-10-05 at 5 52 59 PM

This warning is from this NativeEventEmitter
Screenshot 2021-10-05 at 5 51 55 PM

`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
NativeEventEmitter @ NativeEventEmitter.js:59
(anonymous) @ index.js:14
loadModuleImplementation @ require.js:339
guardedLoadModule @ require.js:209
metroRequire @ require.js:127
(anonymous) @ App.js:11
loadModuleImplementation @ require.js:339
guardedLoadModule @ require.js:209
metroRequire @ require.js:127
(anonymous) @ index.js:7
loadModuleImplementation @ require.js:339
guardedLoadModule @ require.js:200
metroRequire @ require.js:127
(anonymous) @ whyDidYouRender.min.js:8
executeApplicationScript @ RNDebuggerWorker.js:2
(anonymous) @ RNDebuggerWorker.js:2

### PR DESCRIPTION
**Pull request by mlecoq**
to fix #200

### CODE REVIEW

**Comment by jplandry908** [comment]
I just upgraded from react-native 0.64.* to 0.65.* and started noticing this 'new NativeEventEmitter()' was called with a non-null argument without the required 'removeListeners' method error. After a quick search, I came across this issue. However, it appears that it was already fixed? I have the latest version but still seeing the error.

In my 'componentDidMount', I am calling:
Orientation.addOrientationListener(this._onOrientationDidChange);

In my 'componentWillUnmount', I am calling:
Orientation.removeOrientationListener(this._onOrientationDidChange);

And my function just sets the state:
  _onOrientationDidChange = orientation => {
    this.setState({
      orientation: orientation,
    });
  };
  
  If I remove the 'addOrientationListener' statement, the warning goes away.

**Comment by mlecoq** [comment]
@jplandry908 I'll have a look

**Comment by mlecoq** [comment]
@jplandry908 you are right, I will make a second PR for your case

**Comment by jplandry908** [comment]
Thanks @mlecoq. I appreciate your support!

**Pull request merged**
