### PR TITLE
ignore on web and desktop

### PR DESCRIPTION
**Pull request by sayem314**
This PR properly handles platform-specific code, on web and desktop instead of throwing error it would simply ignore for cross-platform compatibility.

### CODE REVIEW

**Comment by wonday** [comment]
Thank you.

**Comment by euharrison** [comment]
A suggestion is to use `.native.js` instead of `.ios.js` and `.android.js`
https://reactnative.dev/docs/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web

**Comment by sayem314** [comment]
@euharrison then wouldn't it break on windows? And this package has some difference between ios and android.

**Comment by r0b0t3d** [comment]
Hi, I got problem with android and ios. It always run code in `index.js` instead of `index.android.js` and `index.ios.js`. 
@euharrison suggest also not working then. I have to rename index -> orientation to make it works.

@wonday This PR breaks `android` and `ios` platform. I will open another PR.

**Comment by sayem314** [comment]
@r0b0t3d there is some broken setup where this happens. If this PR breaks for everyone how does my app on AppStore and play-store works just fine?

**Comment by r0b0t3d** [comment]
@sayem314 Did you point to master branch in your package.json?

**Comment by r0b0t3d** [comment]
@sayem314 waiting to hear from you. If everything works well on your side, I will create another PR to see whether there is other folks got same problem like me.

**Comment by sayem314** [comment]
@r0b0t3d there is only one branch.
`yarn add wonday/react-native-orientation-locker`

**Comment by r0b0t3d** [comment]
Your PR got merged but not release yet. If you'd like to check out your PR, please run this
```
yarn add https://github.com/wonday/react-native-orientation-locker.git#master
```

**Pull request merged**
