### PR TITLE
Use union instead of enum for OrientationType

### PR DESCRIPTION
**Pull request by tylorr**
This is the more idiomatic way of doing this in Typescript

### CODE REVIEW

**Comment by wonday** [comment]
Thank you.

**Comment by Archigog** [comment]
Hello,

I don't understand this change you've made. When trying to the orientation, or when you want to check the orientation, you can't use `OrientationType.PORTRAIT` anymore, for example. Now you're forced to use a string, which is, I think, worse than referencing the enum.

Or am I missing something here ?

Still, thanks for the good work :)

**Comment by tylorr** [comment]
String literal unions are type safe and auto completed just like enums, I don't think it's worse. There is an option to use a combination of string enum (not numeric) and string literal union which would support both and still be type safe.

**Comment by ThomasCarca** [comment]
What are the pros of literal unions over enums ? I would myself choose enums over literal unions in general but I might be unaware of some caveats.

**Pull request merged**
